### PR TITLE
Parse and register custom scalars before introspection

### LINKED ISSUE #72: Exception when using custom scalars inside .graphql schema
Type generation fails with `Unable to resolve reference to type MyCustomScalar` if the schema contains custom scalars. This happens only if using `.graphql` schema when calling `Introspection.fromSchemaDefinition`. The reason for this is that when using schema first in `graphql-dotnet` you have to register your custom scalars directly after parsing the schema, [here](https://graphql-dotnet.github.io/docs/getting-started/custom-scalars#3-register-the-custom-scalar-within-your-schema) is the docs and here is how it looks like:
```csharp
var schema = Schema.For(...);
schema.RegisterType(new MyBooleanGraphType());
```

I was working on a fix for this and my idea was to parse the schema to get the custom scalars out of it and register the types, which would look like this (pseudocode):
```fsharp
let graphqlServer = GraphQL.Types.Schema.For(definition, configureSchemaBuilder)
let types = GraphQLParser.Parser.Parse(definition) // parse the schema into a graphql document to filter scalars

getCustomScalars types |> buildGraphTypes |> |> Seq.iter graphqlServer.RegisterType
let schemaJson = graphqlServer.ExecuteAsync(...)
```

This seems to work, however it does seem pretty inefficient since the schema is parsed many times - first `graphq-dotnet` parses it in `GraphQL.Types.Schema.For`, then I parse it again to get the scalars, then `Snowflaqe` parses it once more to convert from `json` to its internal representation. 

So I started thinking that maybe we could parse the result of `GraphQLParser.Parser.Parse(definition)` directly into the internal data structures `Snowflaqe` uses for type generation? This of course would only be necessary for schemas defined in `.graphql`. Any thoughts on this, @Zaid-Ajaj ?

FYI, @Yakimych @danielstarck 🙂

### PR DESCRIPTION
**Pull request by MargaretKrutikova**
Fix #72

### CODE REVIEW

**Review by Zaid-Ajaj — APPROVED** [review]
The implementation looks great! I will merge and publish when I have access to my laptop

**Comment by Zaid-Ajaj** [comment]
Snowflaqe v1.38 has been published 🚀

**Comment by MargaretKrutikova** [comment]
Cool, thanks! I think the build is failing though, `The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.`, [log](https://ci.appveyor.com/project/Zaid-Ajaj/snowflaqe/builds/43766775#L163). Do we need to install the right SDK version in `appveyor.yml` [here](https://github.com/Zaid-Ajaj/Snowflaqe/blob/master/appveyor.yml#L9)?

**Comment by Zaid-Ajaj** [comment]
The current SDK is fine, I only accidentally changed the target framework of the build project from net5 to net6, easy to fix

**Pull request merged**
